### ISSUE TITLE
[Question] How to set class path for external jars in management center

### ISSUE THREAD

**Issue by nik048** [hazelcast/charts#152]
Is there a way to set the or pass external jar as mentioned [here](https://docs.hazelcast.org/docs/management-center/latest/manual/html/index.html#starting-with-an-extra-classpath)

Need to pass the jar so mc can show it's [value](https://docs.hazelcast.org/docs/management-center/latest/manual/html/index.html#map-browser) in the ui. 

Thanks

**Comment by hasancelik** [comment]
Hi @nik048, 

Unfortunately existing Management Center Helm templates does not support custom volumes. Hazelcast IMDG templates have it, similar approach can be apply to MC as well:
https://github.com/hazelcast/charts/blob/master/stable/hazelcast/templates/statefulset.yaml#L106

I will check possible solutions and keep you posted.

**Comment by nik048** [comment]
Thanks @hasancelik, was able to use the same way as in statefulset.yaml!

In mc console still getting this error for viewing the values (`m.values`) even after passing the jar
`Server request error: Failed to execute console command on member 10.42.0.11:5701 from cluster dev: com.hazelcast.nio.serialization.HazelcastSerializationException: java.lang.ClassNotFoundException: com.example.springcache.model.Blog`

any idea?

**Comment by hasancelik** [comment]
Hi @nik048,

I have prepared [PR](https://github.com/hazelcast/charts/pull/155) for custom volume enhancement Management Center and its documentation. And also I have tried your scenario with this enhancement at GKE:
<img width="1006" alt="Screen Shot 2020-09-11 at 12 16 25" src="https://user-images.githubusercontent.com/6005622/92922263-35717880-f43e-11ea-89f7-afd630239f44.png">

At my first try, I reproduced your issue directly. To fix the issue, I added my jars into Hazelcast IMDG pods via using `customVolume`. Could you try it at your local?

**Comment by leszko** [comment]
@hasancelik can we close this one?

**Comment by hasancelik** [comment]
@leszko, actually I have re-opened it to get approval from @nik048 but I think we can close it for now. @nik048, you can re-opened the issue, if solution does not work for your setup.

**Comment by jeusdi** [comment]
I'm getting a similar issue.

My helm values:

```yaml
hazelcast:
  yaml:
    hazelcast:
      network:
        join:
          kubernetes:
            enabled: true
            service-name: ${serviceName}
            namespace: ${namespace}
        rest-api:
          enabled: true
      jet:
        enabled: ${hz.jet.enabled}
      serialization:
        serializers:
          - type-class: me.jeusdi.fhir.hazelcast.model.Practitioner
            class-name: me.jeusdi.fhir.hazelcast.serializer.PractitionerSerializer

customVolume:
  persistentVolumeClaim:
    claimName: hazelcast-jars


mancenter:
  enabled: true
  javaOpts: -Dhazelcast.mc.lock.skip=true
  yaml:
    hazelcast-client:
      network:
        kubernetes:
          enabled: true
          service-name: ${serviceName}
          namespace: ${namespace}
      serialization:
        serializers:
          - type-class: me.jeusdi.fhir.hazelcast.model.Practitioner
            class-name: me.jeusdi.fhir.hazelcast.serializer.PractitionerSerializer
  customVolume:
    persistentVolumeClaim:
      claimName: hazelcast-mancenter-jars

service:
  type: LoadBalancer
```

Complete log message: `kubectl logs -f hazelcast-external-0`:

```
########################################
# JAVA=/usr/bin/java
# JAVA_OPTS=--add-modules java.se --add-exports java.base/jdk.internal.ref=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.nio=ALL-UNNAMED --add-opens java.base/sun.nio.ch=ALL-UNNAMED --add-opens java.management/sun.management=ALL-UNNAMED --add-opens jdk.management/com.sun.management.internal=ALL-UNNAMED -Dhazelcast.logging.type=log4j2 -Dlog4j.configurationFile=file:/opt/hazelcast/config/log4j2.properties -Dhazelcast.config=/opt/hazelcast/config/hazelcast-docker.xml -Djet.custom.lib.dir=/opt/hazelcast/custom-lib -Djava.net.preferIPv4Stack=true -XX:MaxRAMPercentage=80.0 -XX:MaxGCPauseMillis=5 -Dhazelcast.config=/data/hazelcast/hazelcast.yaml -DserviceName=hazelcast-external -Dnamespace=default -Dhz.jet.enabled=true -Dhazelcast.shutdownhook.policy=GRACEFUL -Dhazelcast.shutdownhook.enabled=true -Dhazelcast.graceful.shutdown.max.wait=600
# CLASSPATH=/opt/hazelcast/*:/data/custom:/data/custom/*:/opt/hazelcast/lib:/opt/hazelcast/lib/*:/opt/hazelcast/bin/user-lib:/opt/hazelcast/bin/user-lib/*
########################################
Starting Hazelcast
+ exec /usr/bin/java --add-modules java.se --add-exports java.base/jdk.internal.ref=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.nio=ALL-UNNAMED --add-opens java.base/sun.nio.ch=ALL-UNNAMED --add-opens java.management/sun.management=ALL-UNNAMED --add-opens jdk.management/com.sun.management.internal=ALL-UNNAMED -Dhazelcast.logging.type=log4j2 -Dlog4j.configurationFile=file:/opt/hazelcast/config/log4j2.properties -Dhazelcast.config=/opt/hazelcast/config/hazelcast-docker.xml -Djet.custom.lib.dir=/opt/hazelcast/custom-lib -Djava.net.preferIPv4Stack=true -XX:MaxRAMPercentage=80.0 -XX:MaxGCPauseMillis=5 -Dhazelcast.config=/data/hazelcast/hazelcast.yaml -DserviceName=hazelcast-external -Dnamespace=default -Dhz.jet.enabled=true -Dhazelcast.shutdownhook.policy=GRACEFUL -Dhazelcast.shutdownhook.enabled=true -Dhazelcast.graceful.shutdown.max.wait=600 -cp '/opt/hazelcast/*:/data/custom:/data/custom/*:/opt/hazelcast/lib:/opt/hazelcast/lib/*:/opt/hazelcast/bin/user-lib:/opt/hazelcast/bin/user-lib/*' com.hazelcast.core.server.HazelcastMemberStarter
2022-03-03 21:34:27,975 [ INFO] [main] [c.h.i.c.AbstractConfigLocator]: Loading configuration '/data/hazelcast/hazelcast.yaml' from System property 'hazelcast.config'
2022-03-03 21:34:27,979 [ INFO] [main] [c.h.i.c.AbstractConfigLocator]: Using configuration file at /data/hazelcast/hazelcast.yaml
2022-03-03 21:34:28,270 [ INFO] [main] [c.h.i.c.o.ExternalConfigurationOverride]: Detected external configuration entries in system properties: [hazelcast.jet.enabled=true]
2022-03-03 21:34:28,364 [ INFO] [main] [c.h.s.logo]: [10.42.1.33]:5701 [dev] [5.0.2] 
	+       +  o    o     o     o---o o----o o      o---o     o     o----o o--o--o
	+ +   + +  |    |    / \       /  |      |     /         / \    |         |   
	+ + + + +  o----o   o   o     o   o----o |    o         o   o   o----o    |   
	+ +   + +  |    |  /     \   /    |      |     \       /     \       |    |   
	+       +  o    o o       o o---o o----o o----o o---o o       o o----o    o   
2022-03-03 21:34:28,364 [ INFO] [main] [c.h.system]: [10.42.1.33]:5701 [dev] [5.0.2] Copyright (c) 2008-2021, Hazelcast, Inc. All Rights Reserved.
2022-03-03 21:34:28,365 [ INFO] [main] [c.h.system]: [10.42.1.33]:5701 [dev] [5.0.2] Hazelcast Platform 5.0.2 (20211221 - 18eec9f) starting at [10.42.1.33]:5701
2022-03-03 21:34:28,365 [ INFO] [main] [c.h.system]: [10.42.1.33]:5701 [dev] [5.0.2] Cluster name: dev
2022-03-03 21:34:28,509 [ERROR] [main] [c.h.i.i.Node]: [10.42.1.33]:5701 [dev] [5.0.2] Node creation failed
com.hazelcast.nio.serialization.HazelcastSerializationException: java.lang.ClassNotFoundException: me.jeusdi.fhir.hazelcast.model.Practitioner
	at com.hazelcast.internal.serialization.impl.SerializerHookLoader.load(SerializerHookLoader.java:80) ~[hazelcast-5.0.2.jar:5.0.2]
	at com.hazelcast.internal.serialization.impl.SerializerHookLoader.<init>(SerializerHookLoader.java:55) ~[hazelcast-5.0.2.jar:5.0.2]
	at com.hazelcast.internal.serialization.impl.DefaultSerializationServiceBuilder.registerSerializerHooks(DefaultSerializationServiceBuilder.java:320) ~[hazelcast-5.0.2.jar:5.0.2]
	at com.hazelcast.internal.serialization.impl.DefaultSerializationServiceBuilder.build(DefaultSerializationServiceBuilder.java:243) ~[hazelcast-5.0.2.jar:5.0.2]
	at com.hazelcast.internal.serialization.impl.DefaultSerializationServiceBuilder.build(DefaultSerializationServiceBuilder.java:57) ~[hazelcast-5.0.2.jar:5.0.2]
	at com.hazelcast.instance.impl.DefaultNodeExtension.createSerializationService(DefaultNodeExtension.java:348) ~[hazelcast-5.0.2.jar:5.0.2]
	at com.hazelcast.instance.impl.DefaultNodeExtension.createSerializationService(DefaultNodeExtension.java:302) ~[hazelcast-5.0.2.jar:5.0.2]
	at com.hazelcast.instance.impl.Node.<init>(Node.java:242) [hazelcast-5.0.2.jar:5.0.2]
	at com.hazelcast.instance.impl.HazelcastInstanceImpl.createNode(HazelcastInstanceImpl.java:149) [hazelcast-5.0.2.jar:5.0.2]
	at com.hazelcast.instance.impl.HazelcastInstanceImpl.<init>(HazelcastInstanceImpl.java:118) [hazelcast-5.0.2.jar:5.0.2]
	at com.hazelcast.instance.impl.HazelcastInstanceFactory.constructHazelcastInstance(HazelcastInstanceFactory.java:211) [hazelcast-5.0.2.jar:5.0.2]
	at com.hazelcast.instance.impl.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:190) [hazelcast-5.0.2.jar:5.0.2]
	at com.hazelcast.instance.impl.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:128) [hazelcast-5.0.2.jar:5.0.2]
	at com.hazelcast.core.Hazelcast.newHazelcastInstance(Hazelcast.java:95) [hazelcast-5.0.2.jar:5.0.2]
	at com.hazelcast.core.server.HazelcastMemberStarter.main(HazelcastMemberStarter.java:47) [hazelcast-5.0.2.jar:5.0.2]
Caused by: java.lang.ClassNotFoundException: me.jeusdi.fhir.hazelcast.model.Practitioner
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581) ~[?:?]
	at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
	at com.hazelcast.internal.nio.ClassLoaderUtil.tryLoadClass(ClassLoaderUtil.java:294) ~[hazelcast-5.0.2.jar:5.0.2]
	at com.hazelcast.internal.nio.ClassLoaderUtil.loadClass(ClassLoaderUtil.java:254) ~[hazelcast-5.0.2.jar:5.0.2]
	at com.hazelcast.internal.serialization.impl.SerializerHookLoader.load(SerializerHookLoader.java:78) ~[hazelcast-5.0.2.jar:5.0.2]
	... 14 more
2022-03-03 21:34:28,516 [ INFO] [main] [c.h.i.i.NodeExtension]: [10.42.1.33]:5701 [dev] [5.0.2] Destroying node NodeExtension.
Exception in thread "main" com.hazelcast.nio.serialization.HazelcastSerializationException: java.lang.ClassNotFoundException: me.jeusdi.fhir.hazelcast.model.Practitioner
	at com.hazelcast.internal.serialization.impl.SerializerHookLoader.load(SerializerHookLoader.java:80)
	at com.hazelcast.internal.serialization.impl.SerializerHookLoader.<init>(SerializerHookLoader.java:55)
	at com.hazelcast.internal.serialization.impl.DefaultSerializationServiceBuilder.registerSerializerHooks(DefaultSerializationServiceBuilder.java:320)
	at com.hazelcast.internal.serialization.impl.DefaultSerializationServiceBuilder.build(DefaultSerializationServiceBuilder.java:243)
	at com.hazelcast.internal.serialization.impl.DefaultSerializationServiceBuilder.build(DefaultSerializationServiceBuilder.java:57)
	at com.hazelcast.instance.impl.DefaultNodeExtension.createSerializationService(DefaultNodeExtension.java:348)
	at com.hazelcast.instance.impl.DefaultNodeExtension.createSerializationService(DefaultNodeExtension.java:302)
	at com.hazelcast.instance.impl.Node.<init>(Node.java:242)
	at com.hazelcast.instance.impl.HazelcastInstanceImpl.createNode(HazelcastInstanceImpl.java:149)
	at com.hazelcast.instance.impl.HazelcastInstanceImpl.<init>(HazelcastInstanceImpl.java:118)
	at com.hazelcast.instance.impl.HazelcastInstanceFactory.constructHazelcastInstance(HazelcastInstanceFactory.java:211)
	at com.hazelcast.instance.impl.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:190)
	at com.hazelcast.instance.impl.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:128)
	at com.hazelcast.core.Hazelcast.newHazelcastInstance(Hazelcast.java:95)
	at com.hazelcast.core.server.HazelcastMemberStarter.main(HazelcastMemberStarter.java:47)
Caused by: java.lang.ClassNotFoundException: me.jeusdi.fhir.hazelcast.model.Practitioner
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at com.hazelcast.internal.nio.ClassLoaderUtil.tryLoadClass(ClassLoaderUtil.java:294)
	at com.hazelcast.internal.nio.ClassLoaderUtil.loadClass(ClassLoaderUtil.java:254)
	at com.hazelcast.internal.serialization.impl.SerializerHookLoader.load(SerializerHookLoader.java:78)
	... 14 more
```

My jar is present into `/data/custom` and also my class is presnet inside this jar.

However, I'm getting `ClassNotFoundException: me.jeusdi.fhir.hazelcast.model.Practitioner`.

Any ideas?

**Comment by Never-say-never** [comment]
Same issue, any update on this?
