### ISSUE TITLE
Question: Hazelcast IMDG open source edition v4.1.1 CP Subsystem Kubernetes

### ISSUE THREAD

**Issue by jisnardo** [hazelcast/charts#202]
Hi,

according to:

https://docs.hazelcast.com/imdg/latest/#hazelcast-imdg-editions

```
Editions

This Reference Manual covers all editions of Hazelcast IMDG. Throughout this manual:

Hazelcast or Hazelcast IMDG refers to the open source edition of Hazelcast in-memory data grid middleware. Hazelcast is also the name of the company (Hazelcast, Inc.) providing the Hazelcast product.

Hazelcast IMDG Pro is a commercially licensed edition of Hazelcast IMDG which provides CP Subsystem Persistence, Hot Restart Persistence & Unlimited Members on Hazelcast Management Center (This is restricted to 3 members on the freely available but unlicensed version of Management Center)

Hazelcast IMDG Enterprise is a commercially licensed edition of Hazelcast IMDG which provides all the features of the Pro Edition, plus High-Density Memory Store, Security Suite (RBAC, TLS, Mutual Auth, Client Certificates), WAN Replication (Sync data between two geo-replicated clusters) & Blue/Green Deployments.

The Pro and Enterprise editions offer all the features of the open source edition.
```

Does Hazelcast IMDG open source edition offers CP Subsystem Persistence or only CP Subsystem with no persistence option?

I was able to use CP Subsystem for:

https://github.com/hazelcast/charts/tree/master/stable/hazelcast

```
jisnardo@edxxxx:~$ helm3 search repo hazelcast -l
NAME                              	CHART VERSION	APP VERSION	DESCRIPTION                                       
hazelcast/hazelcast               	3.6.1        	4.1.1      	Hazelcast IMDG is the most widely used in-memor...
```

Later I've found this:

Verify CP Subsystem usage on Kubernetes #262

https://github.com/hazelcast/hazelcast-kubernetes/issues/262

Update hazelcast/hazelcast-enterprise with CP Subsystem Persistence

https://github.com/hazelcast/charts/issues/176

So... the same solution should work for Hazelcast IMDG open source edition or only as (Enterprise Feature) if there is not backported to the Hazelcast IMDG open source chart eddition?

Thanks in advance.

**Comment by leszko** [comment]
Hazelcast Open Source offers CP Subsystem, but without persistence. You need Hazelcast Enterprise for the CP Subsystem Persistence.

**Comment by jisnardo** [comment]
As expected:

```
jisnardo@edxxxx:~$ kubectl -n test logs hz4test-hazelcast-0
...
java.lang.IllegalStateException: CP persistence requires Hazelcast Enterprise Edition
    at com.hazelcast.instance.impl.DefaultNodeExtension.checkPersistenceAllowed(DefaultNodeExtension.java:163) ~[hazelcast-all-4.1.1.jar:4.1.1]
    at com.hazelcast.instance.impl.DefaultNodeExtension.<init>(DefaultNodeExtension.java:148) ~[hazelcast-all-4.1.1.jar:4.1.1]
    at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
    at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:?]
    at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
    at java.lang.reflect.Constructor.newInstance(Constructor.java:490) ~[?:?]
    at com.hazelcast.instance.impl.NodeExtensionFactory.create(NodeExtensionFactory.java:87) ~[hazelcast-all-4.1.1.jar:4.1.1]
    at com.hazelcast.instance.impl.DefaultNodeContext.createNodeExtension(DefaultNodeContext.java:61) ~[hazelcast-all-4.1.1.jar:4.1.1]
    at com.hazelcast.instance.impl.Node.<init>(Node.java:232) [hazelcast-all-4.1.1.jar:4.1.1]
    at com.hazelcast.instance.impl.HazelcastInstanceImpl.createNode(HazelcastInstanceImpl.java:148) [hazelcast-all-4.1.1.jar:4.1.1]
    at com.hazelcast.instance.impl.HazelcastInstanceImpl.<init>(HazelcastInstanceImpl.java:117) [hazelcast-all-4.1.1.jar:4.1.1]
    at com.hazelcast.instance.impl.HazelcastInstanceFactory.constructHazelcastInstance(HazelcastInstanceFactory.java:211) [hazelcast-all-4.1.1.jar:4.1.1]
    at com.hazelcast.instance.impl.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:190) [hazelcast-all-4.1.1.jar:4.1.1]
    at com.hazelcast.instance.impl.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:128) [hazelcast-all-4.1.1.jar:4.1.1]
    at com.hazelcast.core.Hazelcast.newHazelcastInstance(Hazelcast.java:91) [hazelcast-all-4.1.1.jar:4.1.1]
    at com.hazelcast.core.server.HazelcastMemberStarter.main(HazelcastMemberStarter.java:47) [hazelcast-all-4.1.1.jar:4.1.1]
Exception in thread "main" java.lang.IllegalStateException: CP persistence requires Hazelcast Enterprise Edition
    at com.hazelcast.instance.impl.DefaultNodeExtension.checkPersistenceAllowed(DefaultNodeExtension.java:163)
    at com.hazelcast.instance.impl.DefaultNodeExtension.<init>(DefaultNodeExtension.java:148)
    at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
    at com.hazelcast.instance.impl.NodeExtensionFactory.create(NodeExtensionFactory.java:87)
    at com.hazelcast.instance.impl.DefaultNodeContext.createNodeExtension(DefaultNodeContext.java:61)
    at com.hazelcast.instance.impl.Node.<init>(Node.java:232)
    at com.hazelcast.instance.impl.HazelcastInstanceImpl.createNode(HazelcastInstanceImpl.java:148)
    at com.hazelcast.instance.impl.HazelcastInstanceImpl.<init>(HazelcastInstanceImpl.java:117)
    at com.hazelcast.instance.impl.HazelcastInstanceFactory.constructHazelcastInstance(HazelcastInstanceFactory.java:211)
    at com.hazelcast.instance.impl.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:190)
    at com.hazelcast.instance.impl.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:128)
    at com.hazelcast.core.Hazelcast.newHazelcastInstance(Hazelcast.java:91)
    at com.hazelcast.core.server.HazelcastMemberStarter.main(HazelcastMemberStarter.java:47)
```

Thanks @leszko.
