### ISSUE TITLE
`HZ_LICENSEKEY` should not be defined if `hazelcast.licenseKey` and `hazelcast.licenseKeySecretName`  are not defined

### ISSUE THREAD

**Issue by nosan** [hazelcast/charts#253]
In Cloud, we are currently testing `nlc` image and we found an issue:
```
2021-11-03 15:17:56,708 [ INFO[] [main[] [c.h.i.c.AbstractConfigLocator[]: Using configuration file at /data/hazelcast/hazelcast.yaml
Exception in thread "main" java.lang.StringIndexOutOfBoundsException: begin 0, end 5, length 0
    at java.base/java.lang.String.checkBoundsBeginEnd(String.java:3319)
    at java.base/java.lang.String.substring(String.java:1874)
    at com.hazelcast.internal.config.override.ExternalConfigurationOverride.lambda$overwrite$3(ExternalConfigurationOverride.java:89)
    at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
    at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
    at 


```

This happened because of the empty env variable `HZ_LICESENKEY`.

**Comment by hasancelik** [comment]
related to https://github.com/hazelcast/hazelcast/issues/19849
