### ISSUE TITLE
Service Account cannot list statefulsets

### ISSUE THREAD

**Issue by saikirandusari** [hazelcast/charts#316]
Hi there, I'm using 5.2.0-SNAPSHOT and have observed the below error during the Hazelcast member startup.

` [hazelcast-test-dc] [5.2.0-SNAPSHOT] [x.x.x.x]:5702 is STARTING
Exception in thread "hz-k8s-sts-monitor" com.hazelcast.spi.exception.RestClientException: Failure executing: GET at: https://kubernetes.default.svc/apis/apps/v1/namespaces/hazelcast-test/statefulsets. Message: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"statefulsets.apps is forbidden: User \"system:serviceaccount:sa-hazelcast-test:hazelcast-enterprise\" cannot list resource \"statefulsets\" in API group \"apps\" in the namespace \"sa-hazelcast-test\"","reason":"Forbidden","details":{"group":"apps","kind":"statefulsets"},"code":403}. HTTP Error Code: 403
        at com.hazelcast.spi.utils.RestClient.checkResponseCode(RestClient.java:227)
        at com.hazelcast.spi.utils.RestClient.call(RestClient.java:164)
        at com.hazelcast.spi.utils.RestClient.lambda$callWithRetries$0(RestClient.java:134)
        at com.hazelcast.spi.utils.RetryUtils.retry(RetryUtils.java:65)
        at com.hazelcast.spi.utils.RetryUtils.retry(RetryUtils.java:51)
        at com.hazelcast.spi.utils.RestClient.callWithRetries(RestClient.java:134)
        at com.hazelcast.spi.utils.RestClient.get(RestClient.java:126)
        at com.hazelcast.kubernetes.KubernetesClient.lambda$callGet$0(KubernetesClient.java:545)
        at com.hazelcast.spi.utils.RetryUtils.retry(RetryUtils.java:65)
        at com.hazelcast.kubernetes.KubernetesClient.callGet(KubernetesClient.java:541)
        at com.hazelcast.kubernetes.KubernetesClient.access$200(KubernetesClient.java:53)
        at com.hazelcast.kubernetes.KubernetesClient$StsMonitor.run(KubernetesClient.java:711)
        at java.base/java.lang.Thread.run(Thread.java:829)`

Thanks
Sai

**Comment by mtyazici** [comment]
Hi @saikirandusari, there is an open PR #310  for 5.2 improvements. Thanks for the issue!

**Comment by saikirandusari** [comment]
Thank you @mtyazici.
