### ISSUE TITLE
Hazelcast Helm Deploy on IKS not connecting

### ISSUE THREAD

**Issue by moficodes** [hazelcast/charts#91]
This might be a possible duplicate of #86 

Deployed Hazelcast with helm to IKS Cluster. 

```
helm version --short
v3.0.2+g19e47ee
```

```
helm ls
NAME     	NAMESPACE	REVISION	UPDATED                            	STATUS  	CHART           	APP VERSION
hazelcast	default  	1       	2020-01-21 17:44:03.50896 -0500 EST	deployed	hazelcast-2.10.0	3.12.4
```

```
kubectl logs hazelcast-0

########################################
# JAVA_OPTS=-Dhazelcast.mancenter.enabled=false -Djava.net.preferIPv4Stack=true -Djava.util.logging.config.file=/opt/hazelcast/logging.properties -Dhazelcast.config=/data/hazelcast/hazelcast.yaml -DserviceName=hazelcast -Dnamespace=default -Dhazelcast.mancenter.enabled=true -Dhazelcast.mancenter.url=http://hazelcast-mancenter:8080/hazelcast-mancenter -Dhazelcast.shutdownhook.policy=GRACEFUL -Dhazelcast.shutdownhook.enabled=true -Dhazelcast.graceful.shutdown.max.wait=600
# CLASSPATH=/opt/hazelcast/*:/opt/hazelcast/lib/*
# starting now....
########################################
+ exec java -server -Dhazelcast.mancenter.enabled=false -Djava.net.preferIPv4Stack=true -Djava.util.logging.config.file=/opt/hazelcast/logging.properties -Dhazelcast.config=/data/hazelcast/hazelcast.yaml -DserviceName=hazelcast -Dnamespace=default -Dhazelcast.mancenter.enabled=true -Dhazelcast.mancenter.url=http://hazelcast-mancenter:8080/hazelcast-mancenter -Dhazelcast.shutdownhook.policy=GRACEFUL -Dhazelcast.shutdownhook.enabled=true -Dhazelcast.graceful.shutdown.max.wait=600 com.hazelcast.core.server.StartServer
Jan 21, 2020 10:44:08 PM com.hazelcast.config.AbstractConfigLocator
INFO: Loading configuration '/data/hazelcast/hazelcast.yaml' from System property 'hazelcast.config'
Jan 21, 2020 10:44:08 PM com.hazelcast.config.AbstractConfigLocator
INFO: Using configuration file at /data/hazelcast/hazelcast.yaml
Jan 21, 2020 10:44:08 PM com.hazelcast.instance.AddressPicker
INFO: [LOCAL] [dev] [3.12.5] Prefer IPv4 stack is true, prefer IPv6 addresses is false
Jan 21, 2020 10:44:08 PM com.hazelcast.instance.AddressPicker
INFO: [LOCAL] [dev] [3.12.5] Picked [172.30.199.27]:5701, using socket ServerSocket[addr=/0.0.0.0,localport=5701], bind any local is true
Jan 21, 2020 10:44:08 PM com.hazelcast.system
INFO: [172.30.199.27]:5701 [dev] [3.12.5] Hazelcast 3.12.5 (20191210 - 294ff46) starting at [172.30.199.27]:5701
Jan 21, 2020 10:44:08 PM com.hazelcast.system
INFO: [172.30.199.27]:5701 [dev] [3.12.5] Copyright (c) 2008-2019, Hazelcast, Inc. All Rights Reserved.
Jan 21, 2020 10:44:08 PM com.hazelcast.spi.impl.operationservice.impl.BackpressureRegulator
INFO: [172.30.199.27]:5701 [dev] [3.12.5] Backpressure is disabled
Jan 21, 2020 10:44:09 PM com.hazelcast.spi.discovery.integration.DiscoveryService
INFO: [172.30.199.27]:5701 [dev] [3.12.5] Kubernetes Discovery properties: { service-dns: null, service-dns-timeout: 5, service-name: hazelcast, service-port: 0, service-label: null, service-label-value: true, namespace: default, pod-label: null, pod-label-value: null, resolve-not-ready-addresses: true, use-node-name-as-external-address: false, kubernetes-api-retries: 3, kubernetes-master: https://kubernetes.default.svc}
Jan 21, 2020 10:44:09 PM com.hazelcast.spi.discovery.integration.DiscoveryService
INFO: [172.30.199.27]:5701 [dev] [3.12.5] Kubernetes Discovery activated with mode: KUBERNETES_API
Jan 21, 2020 10:44:09 PM com.hazelcast.instance.Node
INFO: [172.30.199.27]:5701 [dev] [3.12.5] Activating Discovery SPI Joiner
Jan 21, 2020 10:44:09 PM com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl
INFO: [172.30.199.27]:5701 [dev] [3.12.5] Starting 2 partition threads and 3 generic threads (1 dedicated for priority tasks)
Jan 21, 2020 10:44:09 PM com.hazelcast.internal.diagnostics.Diagnostics
INFO: [172.30.199.27]:5701 [dev] [3.12.5] Diagnostics disabled. To enable add -Dhazelcast.diagnostics.enabled=true to the JVM arguments.
Jan 21, 2020 10:44:09 PM com.hazelcast.core.LifecycleService
INFO: [172.30.199.27]:5701 [dev] [3.12.5] [172.30.199.27]:5701 is STARTING
Jan 21, 2020 10:44:09 PM com.hazelcast.spi.discovery.integration.DiscoveryService
INFO: [172.30.199.27]:5701 [dev] [3.12.5] Kubernetes plugin discovered availability zone: wdc04
Jan 21, 2020 10:44:09 PM com.hazelcast.kubernetes.KubernetesClient
WARNING: Cannot fetch public IPs of Hazelcast Member PODs, you won't be able to use Hazelcast Smart Client from outside of the Kubernetes network
Jan 21, 2020 10:44:14 PM com.hazelcast.internal.cluster.ClusterService
INFO: [172.30.199.27]:5701 [dev] [3.12.5]

Members {size:1, ver:1} [
	Member [172.30.199.27]:5701 - 18220a66-dc88-434d-9e9a-ab2fe1fb701c this
]

Jan 21, 2020 10:44:14 PM com.hazelcast.internal.management.ManagementCenterService
INFO: [172.30.199.27]:5701 [dev] [3.12.5] Hazelcast will connect to Hazelcast Management Center on address:
http://hazelcast-mancenter:8080/hazelcast-mancenter
Jan 21, 2020 10:44:14 PM com.hazelcast.core.LifecycleService
INFO: [172.30.199.27]:5701 [dev] [3.12.5] [172.30.199.27]:5701 is STARTED
Jan 21, 2020 10:44:19 PM com.hazelcast.internal.management.ManagementCenterService
INFO: [172.30.199.27]:5701 [dev] [3.12.5] Failed to connect to: http://hazelcast-mancenter:8080/hazelcast-mancenter/collector.do
Jan 21, 2020 10:44:19 PM com.hazelcast.client.impl.ClientEngine
INFO: [172.30.199.27]:5701 [dev] [3.12.5] Applying a new client selector :ClientSelector{any}
Jan 21, 2020 10:44:45 PM com.hazelcast.nio.tcp.TcpIpConnection
INFO: [172.30.199.27]:5701 [dev] [3.12.5] Initialized new cluster connection between /172.30.199.27:5701 and /172.30.239.251:43381
Jan 21, 2020 10:44:52 PM com.hazelcast.internal.cluster.ClusterService
INFO: [172.30.199.27]:5701 [dev] [3.12.5]

Members {size:2, ver:2} [
	Member [172.30.199.27]:5701 - 18220a66-dc88-434d-9e9a-ab2fe1fb701c this
	Member [172.30.239.251]:5701 - 805fe633-c23b-43da-b5e1-7090f3e1069e
]

Jan 21, 2020 10:45:22 PM com.hazelcast.nio.tcp.TcpIpConnection
INFO: [172.30.199.27]:5701 [dev] [3.12.5] Initialized new cluster connection between /172.30.199.27:5701 and /172.30.199.43:40657
Jan 21, 2020 10:45:29 PM com.hazelcast.internal.cluster.ClusterService
INFO: [172.30.199.27]:5701 [dev] [3.12.5]

Members {size:3, ver:3} [
	Member [172.30.199.27]:5701 - 18220a66-dc88-434d-9e9a-ab2fe1fb701c this
	Member [172.30.239.251]:5701 - 805fe633-c23b-43da-b5e1-7090f3e1069e
	Member [172.30.199.43]:5701 - 3b36c99b-7df8-4278-9b6c-2d58db0d05ba
]

Jan 21, 2020 10:46:24 PM com.hazelcast.internal.management.ManagementCenterService
INFO: [172.30.199.27]:5701 [dev] [3.12.5] Failed to pull tasks from Management Center
```

Visiting http://$MANCENTER_IP:8080/hazelcast-mancenter 
gives
![image](https://user-images.githubusercontent.com/14829780/72850956-53545800-3c78-11ea-95ef-c2cd980a9b08.png)

Not sure where to look for debugging.

**Comment by moficodes** [comment]
Oh and 

```
kubectl logs hazelcast-mancenter-0

2020-01-21 23:04:23 [qtp667821226-27] WARN  org.eclipse.jetty.server.HttpChannel - /hazelcast-mancenter/getTask.do
java.lang.NullPointerException: null
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1602)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:540)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1700)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1345)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:480)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1667)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1247)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:61)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:505)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:370)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:267)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:786)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:743)
	at java.base/java.lang.Thread.run(Unknown Source)
```

return the above

**Comment by mesutcelik** [comment]
Hi @moficodes ,
Can you please check if PV and PVC has any problem?
https://github.com/hazelcast/charts#why-is-management-center-pod-in-pending-state

**Comment by moficodes** [comment]
Oh man. Github notification is failing me big time. 
The PV and PVC deployed fine. 

```
kubectl get pv

pvc-09f46b27-42d7-11ea-8956-0a44cb0c30d7   20Gi       RWO            Delete           Bound    hazelcast/hazelcast-mancenter   ibmc-file-bronze            112s

kubectl get pvc

hazelcast-mancenter   Bound    pvc-09f46b27-42d7-11ea-8956-0a44cb0c30d7   20Gi       RWO            ibmc-file-bronze   3m32s

kubectl get po

NAME                    READY   STATUS    RESTARTS   AGE
hazelcast-0             1/1     Running   0          4m18s
hazelcast-1             1/1     Running   0          3m44s
hazelcast-2             1/1     Running   0          3m2s
hazelcast-mancenter-0   1/1     Running   0          4m19s

kubectl get svc
NAME                  TYPE           CLUSTER-IP      EXTERNAL-IP    PORT(S)                        AGE
hazelcast             ClusterIP      None            <none>         5701/TCP                       4m36s
hazelcast-mancenter   LoadBalancer   172.21.34.122   <ExtIP>        8080:32597/TCP,443:31808/TCP   4m36s
```

I would probably try to manually deploy this and see if that works.

**Comment by mesutcelik** [comment]
Hi @emre-aydin @puzpuzpuz ,
Do you have any idea of this NPE? https://github.com/hazelcast/charts/issues/91#issuecomment-576928393

**Comment by puzpuzpuz** [comment]
Hi @mesutcelik 

I didn't see this one before. Which MC version by the helm? Is it 3.12.6?

Is it possible to sniff POST `/hazelcast-mancenter/getTask.do` HTTP request somehow? Or at least to enable debug logs in MC (see [this ref manual section](https://docs.hazelcast.org/docs/management-center/3.12.6/manual/html/index.html#configuring-logging))?

**Comment by mesutcelik** [comment]
Hi @moficodes ,
Are you still experiencing this or it is resolved on your side?

**Comment by leszko** [comment]
Close due to inactivity
